/**
 * @file prerender-seo.ts
 * @description Build-time SEO page generation. Runs automatically after
 * `npm run build` (the `postbuild` script) and turns the single-page dist/
 * into a set of crawler-ready static entry points:
 *
 *   dist/index.html                 <- home, rewritten in place
 *   dist/menu/index.html            <- one per public + legal page
 *   dist/stores/<slug>/index.html   <- one per PUBLISHED store (LocalBusiness JSON-LD)
 *   dist/careers/<slug>/index.html  <- one per PUBLISHED vacancy (JobPosting)
 *   dist/news/<slug>/index.html     <- one per PUBLISHED news post (NewsArticle)
 *   dist/sitemap.xml
 *   dist/robots.txt
 *   dist/seo-manifest.json          <- safe content hash + counts (no secrets)
 *
 * Each generated page is a copy of the built app shell with the <head>
 * rewritten: unique <title>, meta description, canonical URL, Open Graph +
 * Twitter cards (with an ABSOLUTE og:image) and JSON-LD structured data.
 * Link-preview crawlers (WhatsApp, iMessage, Facebook, Slack…) do not run
 * JavaScript, so this static head is what they see; Google additionally
 * renders the app itself for body content.
 *
 * SOURCE OF TRUTH (OPT-02-C1.2): **Supabase is the production source**. This
 * script no longer imports DEFAULT_SITE_CONTENT / INITIAL_* seed modules — it
 * receives a validated PublicContentSnapshot from scripts/load-public-content.ts
 * (production reads Supabase and FAILS CLOSED; development may fall back to the
 * bundled seeds, clearly stamped source: 'development-defaults'). The pages,
 * the sitemap and the JSON-LD are all derived from the SAME filtered snapshot,
 * and the manifest records the one canonical content hash so static crawler
 * output can be proven equal to the live database (see scripts/seo-live-parity).
 *
 * SITE_URL env var overrides the canonical origin (default milkpop.uk).
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

import { storeSlug, vacancySlug, postSlug } from '../src/lib/router';
import { isReal } from '../src/lib/publishRules';
import { parseOpeningHours } from '../src/lib/openingHours';
import {
  legalDescription,
  articleDescription,
  publicLegalName,
  socialProfiles,
  validCoordinates,
} from '../src/lib/publicContentSnapshot';
import type { PublicContentSnapshot, PublicContentSnapshotMetadata } from '../src/lib/publicContentSnapshot';
import type { SiteSettings } from '../src/types';
import { loadPublicContent, resolveDeploymentMode, buildTimestamp } from './load-public-content';

const DIST = path.resolve(process.cwd(), 'dist');
const SITE_URL = (process.env.SITE_URL || 'https://milkpop.uk').replace(/\/+$/, '');
const BUILD_DATE = buildTimestamp().toISOString().slice(0, 10);

// The one 1200×630 social share card (generated by scripts/generate-og-card.mjs,
// committed) and the real logo — the mascot PNG is the wrong shape for both jobs.
const OG_IMAGE = `${SITE_URL}/brand/og-card.png`;
const LOGO = `${SITE_URL}/brand/sticker_logo_blue.png`;

/** Canonical URL form: trailing slash on every non-home path (matches
 *  routeToPath in src/lib/router.ts). */
const canonicalUrl = (route: string) => SITE_URL + (route === '/' ? '/' : `${route}/`);

/** A build-date fallback ISO date; snapshots carry real DB timestamps where
 *  available so we don't pretend every record was published on the build day. */
const dateOrBuild = (value?: string): string => {
  if (value) {
    const d = new Date(value);
    if (!Number.isNaN(d.getTime())) return d.toISOString().slice(0, 10);
  }
  return BUILD_DATE;
};

interface PageDef {
  route: string;
  title: string;
  description: string;
  priority: string;
  jsonLd?: Record<string, unknown>[];
  ogType?: 'website' | 'article';
  preloadImage?: string;
}

/* ------------------------------------------------------------------ */
/*  schema.org helpers                                                  */
/* ------------------------------------------------------------------ */

const MENU_SECTION_LABELS: Record<string, string> = {
  milkshakes: 'Milkshakes', smoothies: 'Smoothies', soft_serve: 'Soft Serve', slush: 'Slush', extras: 'Extras',
};
function menuLd(snapshot: PublicContentSnapshot): Record<string, unknown> {
  const sections = Object.entries(MENU_SECTION_LABELS)
    .map(([key, label]) => ({
      '@type': 'MenuSection',
      name: label,
      hasMenuItem: snapshot.menuItems.filter((i) => i.category === key).map((i) => ({
        '@type': 'MenuItem',
        name: i.name,
        description: i.description,
        offers: { '@type': 'Offer', price: Number(i.price).toFixed(2), priceCurrency: 'GBP' },
      })),
    }))
    .filter((sec) => sec.hasMenuItem.length > 0);
  return {
    '@context': 'https://schema.org',
    '@type': 'Menu',
    name: 'Milk Pop Menu',
    url: canonicalUrl('/menu'),
    inLanguage: 'en-GB',
    hasMenuSection: sections,
  };
}

/* ------------------------------------------------------------------ */
/*  Page definitions — ALL derived from the validated snapshot          */
/* ------------------------------------------------------------------ */

function buildPages(snapshot: PublicContentSnapshot): PageDef[] {
  const seo = snapshot.siteContent.seo;
  const legal = snapshot.siteContent.legal;
  const settings = snapshot.siteSettings;

  const organisationLd: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: isReal(settings.brandName) ? settings.brandName : 'Milk Pop',
    url: SITE_URL + '/',
    logo: LOGO,
    // Only genuine social URLs — empty settings values are omitted (they are
    // hidden on the site too), in a fixed order that matches the content hash.
    sameAs: socialProfiles(settings),
  };
  const legalName = publicLegalName(settings);
  if (legalName) organisationLd.legalName = legalName;

  const pages: PageDef[] = [
    { route: '/', title: seo.home.title, description: seo.home.description, priority: '1.0', jsonLd: [organisationLd], preloadImage: '/brand/mascot_wave.webp' },
    { route: '/menu', title: seo.menu.title, description: seo.menu.description, priority: '0.8', jsonLd: [menuLd(snapshot)] },
    { route: '/stores', title: seo.stores.title, description: seo.stores.description, priority: '0.8' },
    { route: '/about', title: seo.about.title, description: seo.about.description, priority: '0.8' },
    { route: '/contact', title: seo.contact.title, description: seo.contact.description, priority: '0.8' },
  ];

  // Opening-day publication switches control the generated pages as well as
  // the SPA navigation. Disabled programmes do not enter the sitemap, static
  // HTML or noscript navigation and can be enabled later in Website Studio.
  if (settings.showCareers) pages.push({ route: '/careers', title: seo.careers.title, description: seo.careers.description, priority: '0.8' });
  if (settings.showFranchise) pages.push({ route: '/franchise', title: seo.franchise.title, description: seo.franchise.description, priority: '0.8' });
  if (settings.showNews) pages.push({ route: '/news', title: seo.news.title, description: seo.news.description, priority: '0.8' });

  // Core legal pages are always published. Franchise disclosure follows the
  // franchise programme so the site never advertises an unpublished offer.
  (['privacy', 'gdpr'] as const).forEach((key) => {
    pages.push({
      route: `/${key}`,
      title: `${legal[key].title} | Milk Pop`,
      description: legalDescription(legal[key].body),
      priority: '0.5',
    });
  });
  if (settings.showFranchise) {
    pages.push({
      route: '/fdd',
      title: `${legal.fdd.title} | Milk Pop`,
      description: legalDescription(legal.fdd.body),
      priority: '0.5',
    });
  }

  // One crawlable page per PUBLISHED store (LocalBusiness). The snapshot has
  // already dropped incomplete stores via hasRealStoreIdentity, so no
  // placeholder location can reach Google.
  for (const store of snapshot.stores) {
    const slug = storeSlug(store);
    const address: Record<string, unknown> = {
      '@type': 'PostalAddress',
      streetAddress: store.address,
      addressCountry: 'GB',
    };
    if (isReal(store.postcode)) address.postalCode = store.postcode;
    const ld: Record<string, unknown> = {
      '@context': 'https://schema.org',
      '@type': 'IceCreamShop',
      name: store.name,
      url: canonicalUrl(`/stores/${slug}`),
      image: OG_IMAGE,
      priceRange: '£',
      address,
      servesCuisine: 'Milkshakes, Smoothies, Soft Serve, Slush',
      hasMenu: canonicalUrl('/menu'),
    };
    const coords = validCoordinates(store.coordinates);
    if (coords) ld.geo = { '@type': 'GeoCoordinates', latitude: coords.lat, longitude: coords.lng };
    if (isReal(store.phone)) ld.telephone = store.phone;
    if (isReal(store.email)) ld.email = store.email;
    const hoursSpec = parseOpeningHours(store.openingHours);
    if (hoursSpec.length > 0) ld.openingHoursSpecification = hoursSpec;

    const descParts = [store.address + (isReal(store.postcode) ? `, ${store.postcode}` : '')];
    if (isReal(store.openingHours)) descParts.push(store.openingHours);
    pages.push({
      route: `/stores/${slug}`,
      title: `${store.name} — Opening Hours & Location | Milk Pop`,
      description: descParts.join('. ') + '.',
      priority: '0.7',
      jsonLd: [ld],
    });
  }

  // One crawlable page per PUBLISHED vacancy (JobPosting → Google Jobs). Only
  // isPublishableVacancy records survive into the snapshot.
  for (const job of settings.showCareers ? snapshot.vacancies : []) {
    const route = `/careers/${vacancySlug(job)}`;
    const li = (items: string[]) => (items || []).map((i) => `<li>${i}</li>`).join('');
    const descriptionHtml =
      `<p>${job.roleDescription}</p>` +
      `<h3>Requirements</h3><ul>${li(job.requirements)}</ul>` +
      `<h3>Responsibilities</h3><ul>${li(job.responsibilities)}</ul>`;

    // Prefer the real DB timestamp; fall back to the build date only when the
    // snapshot carries no timestamp (development-defaults / fixtures).
    const datePosted = dateOrBuild(job.createdAt || job.updatedAt);
    const jobLd: Record<string, unknown> = {
      '@context': 'https://schema.org',
      '@type': 'JobPosting',
      title: job.title,
      datePosted,
      validThrough: new Date(new Date(datePosted).getTime() + 90 * 86400000).toISOString().slice(0, 10),
      description: descriptionHtml,
      hiringOrganization: { '@type': 'Organization', name: 'Milk Pop', sameAs: SITE_URL + '/', logo: LOGO },
      directApply: true,
    };
    const employmentType = job.type === 'Full-time' ? 'FULL_TIME' : job.type === 'Part-time' ? 'PART_TIME' : undefined;
    if (employmentType) jobLd.employmentType = employmentType;

    const store = snapshot.stores.find((st) => st.name.toLowerCase().includes(job.location.toLowerCase()));
    const jobAddress: Record<string, unknown> = { '@type': 'PostalAddress', addressLocality: job.location, addressCountry: 'GB' };
    if (store) {
      jobAddress.streetAddress = store.address;
      if (isReal(store.postcode)) jobAddress.postalCode = store.postcode;
    }
    jobLd.jobLocation = { '@type': 'Place', address: jobAddress };

    const salary = job.salary.match(/£\s*([\d.]+)(?:\s*-\s*£\s*([\d.]+))?/);
    if (salary) {
      const value: Record<string, unknown> = { '@type': 'QuantitativeValue', minValue: Number(salary[1]) };
      if (salary[2]) value.maxValue = Number(salary[2]);
      if (/hour/i.test(job.salary)) value.unitText = 'HOUR';
      jobLd.baseSalary = { '@type': 'MonetaryAmount', currency: 'GBP', value };
    }

    const jobDescParts = [job.type, job.department];
    if (isReal(job.salary)) jobDescParts.push(job.salary);
    pages.push({
      route,
      title: `${job.title} (${job.location}) | Milk Pop Careers`,
      description: `${jobDescParts.join(' · ')}. Apply online at Milk Pop.`,
      priority: '0.7',
      jsonLd: [jobLd],
    });
  }

  // One crawlable page per PUBLISHED news post (NewsArticle). Draft posts were
  // filtered out of the snapshot, so they never enter HTML, sitemap or JSON-LD.
  for (const post of settings.showNews ? snapshot.newsPosts : []) {
    const route = `/news/${postSlug(post)}`;
    const publishedIso = (() => {
      const d = new Date(post.date);
      if (!Number.isNaN(d.getTime())) return d.toISOString();
      const u = new Date(post.updatedAt || post.createdAt || '');
      return Number.isNaN(u.getTime()) ? new Date(`${BUILD_DATE}T00:00:00.000Z`).toISOString() : u.toISOString();
    })();
    pages.push({
      route,
      title: `${post.title} | Milk Pop News`,
      description: articleDescription(post.content),
      priority: '0.6',
      ogType: 'article',
      jsonLd: [{
        '@context': 'https://schema.org',
        '@type': 'NewsArticle',
        headline: post.title,
        description: articleDescription(post.content),
        image: [OG_IMAGE],
        datePublished: publishedIso,
        author: { '@type': 'Organization', name: 'Milk Pop' },
        publisher: { '@type': 'Organization', name: 'Milk Pop', logo: { '@type': 'ImageObject', url: LOGO } },
        mainEntityOfPage: canonicalUrl(route),
      }],
    });
  }

  return pages;
}

/* ------------------------------------------------------------------ */
/*  HTML head rewriting (plain string surgery on the built shell)      */
/* ------------------------------------------------------------------ */

function escapeAttr(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function upsert(html: string, pattern: RegExp, replacement: string): string {
  // A function replacer is used deliberately: the replacement text is built from
  // owner-editable content (titles, descriptions) that can contain `$`, and a
  // string replacer would interpret `$&`, `$'`, `` $` `` and `$$` as special
  // patterns — corrupting the page (worst case `$'` injects the document tail).
  if (pattern.test(html)) return html.replace(pattern, () => replacement);
  return html.replace('</head>', () => `    ${replacement}\n  </head>`);
}

function renderPage(shell: string, page: PageDef, settings: SiteSettings): string {
  const url = canonicalUrl(page.route);
  const title = escapeAttr(page.title);
  const description = escapeAttr(page.description);
  let html = shell;

  html = upsert(html, /<title>[\s\S]*?<\/title>/, `<title>${title}</title>`);
  html = upsert(html, /<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${description}" />`);
  html = upsert(html, /<meta property="og:title" content="[^"]*" \/>/, `<meta property="og:title" content="${title}" />`);
  html = upsert(html, /<meta property="og:description" content="[^"]*" \/>/, `<meta property="og:description" content="${description}" />`);
  html = upsert(html, /<meta property="og:image" content="[^"]*" \/>/, `<meta property="og:image" content="${OG_IMAGE}" />`);
  html = upsert(html, /<meta property="og:image:width" content="[^"]*" \/>/, `<meta property="og:image:width" content="1200" />`);
  html = upsert(html, /<meta property="og:image:height" content="[^"]*" \/>/, `<meta property="og:image:height" content="630" />`);
  html = upsert(html, /<meta property="og:image:alt" content="[^"]*" \/>/, `<meta property="og:image:alt" content="Milk Pop — milkshake bar" />`);
  html = upsert(html, /<meta property="og:type" content="[^"]*" \/>/, `<meta property="og:type" content="${page.ogType ?? 'website'}" />`);
  html = upsert(html, /<meta property="og:site_name" content="[^"]*" \/>/, `<meta property="og:site_name" content="Milk Pop" />`);
  html = upsert(html, /<meta property="og:locale" content="[^"]*" \/>/, `<meta property="og:locale" content="en_GB" />`);
  html = upsert(html, /<meta property="og:url" content="[^"]*" \/>/, `<meta property="og:url" content="${url}" />`);
  html = upsert(html, /<link rel="canonical" href="[^"]*" \/>/, `<link rel="canonical" href="${url}" />`);
  html = upsert(html, /<meta name="twitter:card" content="[^"]*" \/>/, `<meta name="twitter:card" content="summary_large_image" />`);
  html = upsert(html, /<meta name="twitter:title" content="[^"]*" \/>/, `<meta name="twitter:title" content="${title}" />`);
  html = upsert(html, /<meta name="twitter:description" content="[^"]*" \/>/, `<meta name="twitter:description" content="${description}" />`);
  html = upsert(html, /<meta name="twitter:image" content="[^"]*" \/>/, `<meta name="twitter:image" content="${OG_IMAGE}" />`);

  // The built shell carries one explicitly marked route-image preload. Keep
  // exactly one on routes that need it and remove it everywhere else. The
  // marker avoids touching unrelated future image preloads and makes attribute
  // order irrelevant.
  const routeImagePreload = /\s*<link\b(?=[^>]*\bid="mp-route-image-preload")(?=[^>]*\brel="preload")(?=[^>]*\bas="image")[^>]*\/?>\s*/;
  if (page.preloadImage) {
    html = upsert(
      html,
      routeImagePreload,
      `<link id="mp-route-image-preload" rel="preload" as="image" type="image/webp" href="${page.preloadImage}" fetchpriority="high" />`,
    );
  } else {
    html = html.replace(routeImagePreload, '\n');
  }

  /* LAUNCH-POLISH (R4.6): page-specific <noscript> body.
   *
   * These generated pages carry a full <head> — title, description, canonical,
   * Open Graph, Twitter card, JSON-LD — but their <body> was only
   * `<div id="root"></div>`. Social and messaging previews read the head, so
   * they were always fine; a visitor with scripting disabled got a blank page,
   * and so does any crawler that does not execute JavaScript.
   *
   * The block below is NOT an attempt to server-render the app. It is an
   * honest text fallback: the page's own title and description, the same
   * navigation every page shows, and a way to contact us. It is replaced
   * wholesale rather than appended, so the shell's generic copy never
   * duplicates the page-specific copy.
   */
  html = html.replace(
    /<noscript>[\s\S]*?<\/noscript>/,
    () => noscriptBody(page.title, page.description, settings),
  );

  for (const block of page.jsonLd || []) {
    // Escape `<` so a value containing `</script>` cannot break out of the
    // ld+json block, and use a FUNCTION replacer so `$` sequences inside the
    // JSON (e.g. prices, "$&") are inserted literally rather than interpreted.
    const json = JSON.stringify(block).replace(/</g, '\\u003c');
    html = html.replace('</head>', () => `    <script type="application/ld+json">${json}</script>\n  </head>`);
  }

  return html;
}

/* ------------------------------------------------------------------ */
/*  <noscript> fallback body                                            */
/* ------------------------------------------------------------------ */

function noscriptNav(settings: SiteSettings): [string, string][] {
  const links: [string, string][] = [
    ['/menu/', 'Menu'],
    ['/stores/', 'Stores'],
    ['/about/', 'About us'],
    ['/contact/', 'Contact'],
  ];
  if (settings.showCareers) links.splice(3, 0, ['/careers/', 'Careers']);
  if (settings.showFranchise) links.splice(settings.showCareers ? 4 : 3, 0, ['/franchise/', 'Franchise']);
  if (settings.showNews) links.splice(settings.showCareers || settings.showFranchise ? links.length - 1 : 3, 0, ['/news/', 'News']);
  links.push(['/privacy/', 'Privacy notice'], ['/gdpr/', 'Your data rights']);
  if (settings.showFranchise) links.push(['/fdd/', 'Franchise information']);
  return links;
}

/* NOTE: this takes the RAW page title/description, not the values already put
 * through escapeAttr() for the meta tags. Escaping an escaped string turns
 * `&amp;` into `&amp;amp;`, which renders as literal "&amp;" on the page —
 * exactly the bug this comment exists to stop coming back. */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function noscriptBody(title: string, description: string, settings: SiteSettings): string {
  const nav = noscriptNav(settings)
    .map(([href, label]) => `          <li><a href="${href}">${label}</a></li>`)
    .join('\n');
  return [
    '<noscript>',
    '      <div style="max-width:42rem;margin:0 auto;padding:2.5rem 1.25rem;font-family:system-ui,sans-serif;color:#2E2A26;line-height:1.6">',
    `        <h1 style="font-size:1.75rem;margin:0 0 .5rem">${escapeHtml(title)}</h1>`,
    `        <p>${escapeHtml(description)}</p>`,
    '        <p>This site needs JavaScript for its interactive menu, forms and account features. With scripting turned off you can still reach every public page:</p>',
    '        <ul>',
    nav,
    '        </ul>',
    '      </div>',
    '    </noscript>',
  ].join('\n');
}

/* ------------------------------------------------------------------ */
/*  sitemap.xml + robots.txt                                           */
/* ------------------------------------------------------------------ */

function renderSitemap(pages: PageDef[]): string {
  const urls = pages
    .map((p) => {
      const loc = canonicalUrl(p.route);
      return `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${BUILD_DATE}</lastmod>\n    <priority>${p.priority}</priority>\n  </url>`;
    })
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function renderRobots(): string {
  return [
    'User-agent: *',
    'Allow: /',
    '# Staff/admin de-indexing is enforced by X-Robots-Tag (public/_headers) +',
    '# the runtime <meta name="robots"> — a robots.txt Disallow would stop',
    '# Google from ever seeing those noindex signals.',
    '',
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    '',
  ].join('\n');
}

/* ------------------------------------------------------------------ */
/*  Safe SEO manifest — content hash + counts, NEVER any secret        */
/* ------------------------------------------------------------------ */

function buildManifest(
  metadata: PublicContentSnapshotMetadata,
  generatedPages: number,
  published: PublicContentSnapshot,
  suppressed: boolean,
): Record<string, unknown> {
  return {
    schemaVersion: 2,
    source: metadata.source,
    generatedAt: metadata.generatedAt,
    siteUrl: SITE_URL,
    contentHash: metadata.contentHash,
    // `counts` describes what was LOADED. R4.10 Increment 2 adds what was
    // actually PUBLISHED, because on a non-authoritative snapshot the two now
    // differ and a manifest reporting only the first is misleading: it would
    // say menuItems 24 for a build that published none.
    counts: { ...metadata.counts, generatedPages },
    commercialOutputSuppressed: suppressed,
    publishedCounts: {
      menuItems: published.menuItems.length,
      stores: published.stores.length,
      vacancies: published.vacancies.length,
      newsPosts: published.newsPosts.length,
    },
    latestUpdatedAt: metadata.latestUpdatedAt,
  };
}

/* ------------------------------------------------------------------ */
/*  R4.10 INCREMENT 2 — NON-AUTHORITATIVE SNAPSHOTS MAKE NO CLAIMS     */
/* ------------------------------------------------------------------ */

/**
 * A snapshot that did not come from the database may not produce commercial
 * output. Not in production, and NOT in local or preview builds either.
 *
 * WHY THIS IS NOT ALREADY COVERED
 * -------------------------------
 * main() refuses a non-Supabase snapshot in PRODUCTION, and R4.9 G4 proved the
 * running SPA cannot show seed products or prices in real Chromium. Neither
 * covered the artefact this script writes. A development-defaults build emitted
 * schema.org Menu markup carrying seed products WITH PRICES —
 *
 *     {"@type":"MenuItem","name":"Kinder Bueno",
 *      "offers":{"@type":"Offer","price":"5.00","priceCurrency":"GBP"}}
 *
 * — plus a sitemap advertising a seed article. Anything crawled from a preview
 * deploy is a price claim to a consumer and an indexed URL that will outlive the
 * build that produced it: a later real build removes the page, the URL keeps
 * answering 200 with the SPA shell, and the wrong price stays in the index.
 *
 * WHAT SUPPRESSION MEANS
 * ----------------------
 * The business collections are emptied before anything is rendered, so a single
 * decision removes every downstream consequence at once: no MenuItem, no Offer,
 * no price, no per-store / per-vacancy / per-article page, and therefore no
 * dynamic sitemap entry either — the sitemap is built FROM the page list.
 *
 * What deliberately survives: every static route (so /menu/ still exists and
 * shows its honest empty state), and the genuine Organization / WebSite schema,
 * which asserts that a business exists rather than what it sells.
 *
 * The empty result is the honest one. A preview build of a project with no
 * published content SHOULD look like a site with no published content.
 */
function suppressCommercialClaims(
  snapshot: PublicContentSnapshot,
  source: string,
): { snapshot: PublicContentSnapshot; suppressed: boolean } {
  if (source === 'supabase') return { snapshot, suppressed: false };
  return {
    snapshot: { ...snapshot, menuItems: [], stores: [], vacancies: [], newsPosts: [] },
    suppressed: true,
  };
}

/* ------------------------------------------------------------------ */
/*  Main                                                               */
/* ------------------------------------------------------------------ */

async function main(): Promise<void> {
  const shellPath = path.join(DIST, 'index.html');
  if (!existsSync(shellPath)) {
    console.error('prerender-seo: dist/index.html not found — run `npm run build` first.');
    process.exit(1);
  }

  const mode = resolveDeploymentMode(process.env);
  const { snapshot, metadata } = await loadPublicContent({ mode });

  // Belt-and-braces: a production build must be Supabase-sourced. loadPublicContent
  // already fails closed, but assert here so seed fallback can never slip through.
  if (mode === 'production' && metadata.source !== 'supabase') {
    console.error(
      'SEO build failed: production public content did not come from Supabase.\n' +
      'Static seed fallback is prohibited in production.',
    );
    process.exit(1);
  }

  const shell = await readFile(shellPath, 'utf8');

  // R4.10 Increment 2: applies in EVERY mode, not only production. In production
  // this is unreachable (the guard above already exited), which is the point —
  // it is the local and preview builds that were emitting priced seed markup.
  const { snapshot: publishable, suppressed } = suppressCommercialClaims(snapshot, metadata.source);
  if (suppressed) {
    console.warn(
      `prerender-seo: snapshot source is "${metadata.source}", not "supabase" — ` +
      'commercial output SUPPRESSED. No menu items, stores, vacancies or articles ' +
      'will be published, and no MenuItem/Offer/JobPosting structured data or dynamic ' +
      'sitemap entry will be emitted. Static routes still render their empty states.',
    );
  }

  const pages = buildPages(publishable);

  let written = 0;
  for (const page of pages) {
    const html = renderPage(shell, page, publishable.siteSettings);
    const outPath = page.route === '/'
      ? shellPath
      : path.join(DIST, ...page.route.split('/').filter(Boolean), 'index.html');
    await mkdir(path.dirname(outPath), { recursive: true });
    await writeFile(outPath, html, 'utf8');
    written += 1;
  }

  await writeFile(path.join(DIST, 'sitemap.xml'), renderSitemap(pages), 'utf8');
  await writeFile(path.join(DIST, 'robots.txt'), renderRobots(), 'utf8');
  await writeFile(path.join(DIST, 'seo-manifest.json'), JSON.stringify(buildManifest(metadata, written, publishable, suppressed), null, 2) + '\n', 'utf8');
  // Runtime last-known-good bootstrap. Production builds only reach this point
  // with a validated Supabase snapshot; the browser revalidates the file before
  // using it and replaces it with live anonymous data whenever available.
  await writeFile(path.join(DIST, 'public-content.json'), JSON.stringify({ snapshot: publishable, metadata }, null, 2) + '\n', 'utf8');

  console.log(
    `prerender-seo: ${written} pages + sitemap.xml + robots.txt + seo-manifest.json ` +
    `written for ${SITE_URL} [source=${metadata.source}, hash=${metadata.contentHash}, ` +
    `stores=${metadata.counts.stores}, vacancies=${metadata.counts.vacancies}, ` +
    `news=${metadata.counts.publishedNewsPosts}, menu=${metadata.counts.menuItems}]`,
  );
}

main().catch((err) => {
  console.error('prerender-seo failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
