/* r48-outbox-contract.test.mjs — R4.8 Workstream C: durable outbox invariants. */
import { readFileSync } from 'node:fs';
let passed = 0, failed = 0;
const ok = (n) => { passed++; console.log('✔', n); };
const fail = (n, d) => { failed++; console.log('✘', n, d ? `— ${d}` : ''); };
const check = (n, c, d) => (c ? ok(n) : fail(n, d));
const sql = readFileSync('supabase/migration_r48_outbox_and_gates.sql', 'utf8');
const fn = readFileSync('supabase/functions/outbox-dispatch/index.ts', 'utf8');
const spf = sql.slice(sql.indexOf('create or replace function public.submit_public_form'));
check('claim uses FOR UPDATE SKIP LOCKED (no double-claim)', /for update skip locked/i.test(sql));
check('claimed jobs become visibly processing', /set status = 'processing'/.test(sql));
check('bounded retries with exponential backoff', /power\(2,/.test(sql) && /v_max constant int := 6/.test(sql));
check('exhausted/permanent jobs reach dead_letter', /dead_letter/.test(sql) && /dead_lettered_at=now\(\)/.test(sql));
check('provider-unconfigured is a visible blocked_config state', /blocked_config/.test(sql) && /blocked_config/.test(fn));
check('recipient is a KIND, constrained in the schema', /recipient_kind\s+text not null check \(recipient_kind in[\s\S]{0,80}owner_notification/.test(sql));
check('no browser writes: outbox has no authenticated insert/update policy', !/create policy [^;]*on notification_outbox[^;]*for (insert|update)/i.test(sql));
check('claim/mark are revoked from browser roles', /revoke all on function outbox_claim_batch\(int\) from public, anon, authenticated/.test(sql));
const dupIdx = spf.indexOf("'duplicate_replay'");
const enqIdx = spf.indexOf('insert into notification_outbox');
check('enqueue is atomic with the accepted insert (same function body)', enqIdx > 0);
check('duplicate replay returns BEFORE any enqueue (no duplicate e-mail)', dupIdx > 0 && dupIdx < enqIdx);
check('accepted submission stamps the privacy-notice version', /notice_version/.test(spf) && /current_privacy_version\(p_kind\)/.test(spf));
check('commissioning gate fails closed with a typed error', /forms_not_commissioned/.test(spf));
check('signature stays the WP-02.1 five-argument contract', /submit_public_form\(\s*p_kind\s+text,\s*p_row\s+jsonb,\s*p_idempotency_key\s+uuid,\s*p_request_hash\s+text,\s*p_ip_hash\s+text\s*\)/.test(sql));
check('browser roles remain revoked on submit_public_form', /revoke all on function public\.submit_public_form\(text, jsonb, uuid, text, text\) from public, anon, authenticated/.test(sql));
check('worker resolves owner recipient from launch_settings, never payload', /launch_settings\?select=notification_recipient/.test(fn) && !/payload\.(to|recipient)/.test(fn));
check('worker authenticates as service role only', /auth !== SERVICE/.test(fn));
check('customer ack never claims human review', /does not mean a person has reviewed/.test(fn));
check('worker records a heartbeat every run', /record_heartbeat/.test(fn));
console.log(`\nR48-OUTBOX — ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
