#!/usr/bin/env node
/* ============================================================================
 * rpc-parity.test.mjs — every RPC the browser client calls must EXIST in the
 * database the client will actually talk to.
 *
 * WHY THIS EXISTS
 *   The Stage-3 auditor caught the real hazard directly: the WS7 quote/payment
 *   rework DROPPED submit_web_order(jsonb) from the database (see
 *   supabase/migration_stage3_ws7_quote_finalise.sql), but the browser client
 *   still POSTs to /rest/v1/rpc/submit_web_order. Nothing in the suite noticed,
 *   because the RLS matrix proves the DB in isolation and the type/lint gates
 *   never look at the SQL surface. A call to a function PostgREST cannot resolve
 *   fails at runtime with 404 — exactly the class of drift a launch gate should
 *   refuse. This test closes that gap, statically, with no database required so
 *   it can live inside `npm run verify`.
 *
 * WHAT IT COMPARES
 *   CLIENT SIDE  — every rpc/<name> the client references, gathered from src/:
 *                    • bare  rpc/<name>  URL literals (authedRest / fetch)
 *                    • callRpc<…>('<name>', …) wrapper call sites
 *                  (the wrapper's own internal `rpc/${name}` template is not a
 *                   call site and is correctly ignored.)
 *   DATABASE SIDE — the final launch function set, read from the authoritative
 *                  pg_dump of the full chain: supabase/launch-baseline-v1.sql
 *                  (regenerated by `npm run stage3:baseline`, proven canonically
 *                   equal to schema.FRESH-INSTALL-ONLY.sql + the whole migration manifest by the
 *                   WS14 equivalence test). Every CREATE FUNCTION public.<name>.
 *
 * VERDICT
 *   drift = { client-called } \ { db-present }.
 *   Each drift name must appear in scripts/rpc-parity.known-drift.json with a
 *   reason, or the test fails. The allowlist is itself policed: an entry that
 *   is no longer real drift (the client stopped calling it, or the DB now has
 *   it) fails as STALE, so the list cannot quietly rot — when the client is
 *   rebuilt onto the quote/payment flow, the submit_web_order entry MUST be
 *   deleted or this test will fail.
 *
 *   Run: node scripts/rpc-parity.test.mjs   (also wired into npm run verify)
 * ==========================================================================*/
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'src');
const BASELINE = path.join(ROOT, 'supabase', 'launch-baseline-v1.sql');
const ALLOWLIST = path.join(ROOT, 'scripts', 'rpc-parity.known-drift.json');

/* ---- collect every source file under src/ -------------------------------- */
function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...walk(full));
    else if (/\.(ts|tsx|js|jsx|mjs)$/.test(entry)) out.push(full);
  }
  return out;
}

/* ---- CLIENT: which rpc/<name> does the browser reference? ----------------- */
// A bare rpc/<name> URL segment. `[a-z_]` as the first char means the wrapper's
// own `rpc/${name}` template literal is skipped (it starts with `$`), which is
// correct: the wrapper is not a call site, its callers are.
const RE_RPC_PATH = /rpc\/([a-z_][a-z0-9_]*)/g;
// callRpc, with an optional generic type argument, then a string-literal name.
// The generic may itself contain '>' (e.g. Record<string, unknown>[]), so we
// consume up to the opening '(' rather than trying to balance angle brackets.
const RE_CALLRPC = /callRpc\s*(?:<[^(]*>)?\s*\(\s*['"]([a-z_][a-z0-9_]*)['"]/g;

function collectClientRpcs() {
  const found = new Map(); // name -> Set(relative file)
  const files = existsSync(SRC_DIR) ? walk(SRC_DIR) : [];
  for (const file of files) {
    const text = readFileSync(file, 'utf8');
    const rel = path.relative(ROOT, file);
    for (const re of [RE_RPC_PATH, RE_CALLRPC]) {
      re.lastIndex = 0;
      let m;
      while ((m = re.exec(text)) !== null) {
        const name = m[1];
        if (!found.has(name)) found.set(name, new Set());
        found.get(name).add(rel);
      }
    }
  }
  return found;
}

/* ---- DATABASE: the final launch function set ----------------------------- */
const RE_CREATE_FN = /(?:^|\n)\s*create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?([a-z_][a-z0-9_]*)\s*\(/gim;

function collectDbFunctions() {
  if (!existsSync(BASELINE)) {
    console.error(`✖ launch baseline missing: ${path.relative(ROOT, BASELINE)}`);
    console.error('  run `npm run stage3:baseline` to regenerate it from the chain.');
    process.exit(1);
  }
  const set = new Set();
  const collect = (text) => {
    RE_CREATE_FN.lastIndex = 0;
    let m;
    while ((m = RE_CREATE_FN.exec(text)) !== null) set.add(m[1]);
  };
  collect(readFileSync(BASELINE, 'utf8'));

  // The checked-in pg_dump represents the last accepted baseline. Append-only
  // closure migrations may legitimately add RPCs before the next baseline is
  // regenerated, so include every migration in the authoritative ordered
  // ledger. The baseline still protects against historic create/drop drift;
  // this tail scan makes newly added functions visible to the same parity gate.
  const manifest = path.join(ROOT, 'launch', 'migration-manifest.sh');
  const ordered = execFileSync('bash', [manifest, 'upgrade'], { encoding: 'utf8' })
    .trim().split(/\r?\n/).filter(Boolean);
  for (const relative of ordered) {
    const file = path.join(ROOT, relative);
    if (existsSync(file)) collect(readFileSync(file, 'utf8'));
  }
  return set;
}

/* ---- allowlist ----------------------------------------------------------- */
function loadAllowlist() {
  if (!existsSync(ALLOWLIST)) return [];
  const raw = JSON.parse(readFileSync(ALLOWLIST, 'utf8'));
  const entries = Array.isArray(raw) ? raw : raw.knownDrift;
  if (!Array.isArray(entries)) {
    console.error('✖ rpc-parity.known-drift.json must be an array (or {knownDrift: [...]})');
    process.exit(1);
  }
  for (const e of entries) {
    if (!e || typeof e.name !== 'string' || typeof e.reason !== 'string' || !e.reason.trim()) {
      console.error('✖ every allowlist entry needs a non-empty {name, reason}');
      process.exit(1);
    }
  }
  return entries;
}

/* ---- run ----------------------------------------------------------------- */
const client = collectClientRpcs();
const db = collectDbFunctions();
const allow = loadAllowlist();
const allowByName = new Map(allow.map((e) => [e.name, e.reason]));

const clientNames = [...client.keys()].sort();
const drift = clientNames.filter((n) => !db.has(n));

console.log(`rpc-parity: client references ${clientNames.length} RPC(s); ` +
            `launch baseline defines ${db.size} function(s).`);

let failed = 0;

// 1. Real drift that is NOT allow-listed → fail.
const unlisted = drift.filter((n) => !allowByName.has(n));
for (const n of unlisted) {
  failed++;
  const where = [...client.get(n)].join(', ');
  console.log(`  ✖ ${n} — called by client (${where}) but ABSENT from the launch database`);
}

// 2. Drift that IS allow-listed → report, do not fail.
for (const n of drift.filter((n) => allowByName.has(n))) {
  const where = [...client.get(n)].join(', ');
  console.log(`  ⚠ ${n} — known drift (${allowByName.get(n)}) [${where}]`);
}

// 3. Allowlist hygiene: an entry that is no longer real drift is STALE → fail.
for (const e of allow) {
  const stillCalled = client.has(e.name);
  const stillMissing = !db.has(e.name);
  if (!(stillCalled && stillMissing)) {
    failed++;
    const why = !stillCalled
      ? 'the client no longer calls it'
      : 'the database now defines it';
    console.log(`  ✖ stale allowlist entry "${e.name}" — ${why}; remove it from ` +
                'scripts/rpc-parity.known-drift.json');
  }
}

console.log('');
if (failed === 0) {
  const suffix = drift.length ? ` (${drift.length} known-drift, all accounted for)` : '';
  console.log(`✔ RPC PARITY — every client RPC resolves against the launch database${suffix}`);
} else {
  console.log(`✖ RPC PARITY — ${failed} problem(s); see above`);
  process.exit(1);
}
