/**
 * @file drinkArt.ts
 * @description Branded product illustrations for every seeded menu item.
 *
 * The SVGs live in /public/brand/drinks and are generated by
 * scripts/generate-drink-art.mjs in the exact style of the product
 * photography (clear cup, flecked shake, drizzle, blue wave band,
 * caramel wordmark). They act as the DEFAULT image for a menu item:
 *
 *   priority 1 — a real image set on the item (Website Studio upload /
 *                menu_items.image in the database),
 *   priority 2 — the branded illustration below (matched by item id),
 *   priority 3 — the coloured emoji placeholder card.
 *
 * This means the menu looks fully dressed on day one, and every
 * illustration is replaced automatically the moment the owner uploads a
 * real photo for that item — no code changes needed.
 */
import type { MenuItem } from './types';
import { resolveMediaUrl } from './lib/mediaUpload';

export const DRINK_ART: Record<string, string> = {
  m1: '/brand/drinks/m1.svg',   // Kinder Bueno
  m2: '/brand/drinks/m2.svg',   // Ferrero Rocher
  m3: '/brand/drinks/m3.svg',   // Oreo
  m4: '/brand/drinks/m4.svg',   // Snickers
  m5: '/brand/drinks/m5.svg',   // KitKat
  m6: '/brand/drinks/m6.svg',   // Caramel
  m7: '/brand/drinks/m7.svg',   // Biscoff
  m8: '/brand/drinks/m8.svg',   // Vanilla
  m9: '/brand/drinks/m9.svg',   // Strawberry
  m10: '/brand/drinks/m10.svg', // Banana
  sm1: '/brand/drinks/sm1.svg', // Strawberry Banana
  sm2: '/brand/drinks/sm2.svg', // Acai
  sm3: '/brand/drinks/sm3.svg', // Mango Passion Fruit
  sm4: '/brand/drinks/sm4.svg', // Berry Mix
  ss1: '/brand/drinks/ss1.svg', // Classic Cup
  ss2: '/brand/drinks/ss2.svg', // Premium Cup
  ss3: '/brand/drinks/ss3.svg', // Cone
  sl1: '/brand/drinks/sl1.svg', // Blue Slush
  sl2: '/brand/drinks/sl2.svg', // Red Slush
  e1: '/brand/drinks/e1.svg',   // Mix Flavours
  e2: '/brand/drinks/e2.svg',   // Whipped Cream
  e3: '/brand/drinks/e3.svg',   // Extra Nutella
  e4: '/brand/drinks/e4.svg',   // Cookie Crumbs
  e5: '/brand/drinks/e5.svg',   // Marshmallows
};

/** True when the stored image value is a real, displayable source. */
export const hasRealImage = (image?: string) =>
  image !== 'placeholder' && resolveMediaUrl(image) !== undefined;

/**
 * Resolve what to draw for a menu item:
 * a real uploaded image wins, then the branded illustration, then nothing
 * (callers fall back to the emoji card).
 */
export function resolveMenuImage(item: Pick<MenuItem, 'id' | 'image'>): string | null {
  const uploaded = resolveMediaUrl(item.image);
  if (uploaded) return uploaded;
  return DRINK_ART[item.id] ?? null;
}
